sudo: required

language: c

os:
  - linux
  - osx

env:
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08

matrix:
  fast_finish: true

cache:
  directories:
    - /home/travis/.opam/

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh ;
    bash -ex .travis-ocaml.sh ;

script:
  - set -ex ;
    export OPAMYES=1 ;
    eval $(opam config env) ;
    opam pin add phonetic . --no-action ;
    opam update ;
    opam install phonetic --with-test --deps-only ;
    dune build ;
    dune runtest ;
    dune build @runbench ;
